meta_product_name: "ARTHUDDLE"
meta_title: "ARTHUDDLE - Discover your creative potential"
meta_description: "Unlock your artistic side with ARTHUDDLE. Explore hand-picked art classes and events in a range of media, hosted by local artists."
meta_image: "cover.png"
twitter_account: "@arthuddle"


